// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVgO7P_oxg_-JPSHVhoiA5MGv78kK49eQ',
    appId: '1:382840130626:web:7271a16f12d300c7f3f1db',
    messagingSenderId: '382840130626',
    projectId: 'kitakyushu-shukatu',
    authDomain: 'kitakyushu-shukatu.firebaseapp.com',
    storageBucket: 'kitakyushu-shukatu.firebasestorage.app',
    measurementId: 'G-9ED922TBZS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApys698KtNXVMz9sehbfpGeNbS868Km70',
    appId: '1:382840130626:android:c65535a93eb4a00ef3f1db',
    messagingSenderId: '382840130626',
    projectId: 'kitakyushu-shukatu',
    storageBucket: 'kitakyushu-shukatu.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7hk7yk3DheITlxEGVmqTVnOiWkY9CvwM',
    appId: '1:382840130626:ios:72a47c50de7bb618f3f1db',
    messagingSenderId: '382840130626',
    projectId: 'kitakyushu-shukatu',
    storageBucket: 'kitakyushu-shukatu.firebasestorage.app',
    iosBundleId: 'com.example.kitakyushuShukatu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7hk7yk3DheITlxEGVmqTVnOiWkY9CvwM',
    appId: '1:382840130626:ios:72a47c50de7bb618f3f1db',
    messagingSenderId: '382840130626',
    projectId: 'kitakyushu-shukatu',
    storageBucket: 'kitakyushu-shukatu.firebasestorage.app',
    iosBundleId: 'com.example.kitakyushuShukatu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVgO7P_oxg_-JPSHVhoiA5MGv78kK49eQ',
    appId: '1:382840130626:web:eae23cdaaafb60c7f3f1db',
    messagingSenderId: '382840130626',
    projectId: 'kitakyushu-shukatu',
    authDomain: 'kitakyushu-shukatu.firebaseapp.com',
    storageBucket: 'kitakyushu-shukatu.firebasestorage.app',
    measurementId: 'G-P6GT6EEDCX',
  );

}